const TICK_LENGTH = 8
const TICK_MARGIN = 4
const TICK_LINE_HEIGHT = 16
const X_TICK_COUNT_RATIO = 100
const Y_TICK_COUNT_RATIO = 50

export {
  TICK_LENGTH,
  TICK_LINE_HEIGHT,
  TICK_MARGIN,
  X_TICK_COUNT_RATIO,
  Y_TICK_COUNT_RATIO
}
